Module 1 Capstone project
oguntayomicheal/Module-1-Microverse-Capstone-project- pull request #1
Opened 2022-09-15 07:55 UTC by Mike-devloper

- [ ] Added the mobile homepage
- [ ] Added the mobile About page
- [ ] Adapted the mobile home and about pages to desktop
- [ ] Created the featured speakers dynamically

2022-09-15 13:42 UTC, Munsa1 requested changes
Hi @Mike-devloper, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 13:42 UTC, Munsa1 commented on about.html
> +    </footer>
- [ ] Kindly add the correct color for the footer section, the text is `color: white` and the backround is `color: #272A31`.
- [ ] Also align the footer items correctly as they are aligned in the given design, not to the center but to the left and right. You could use `display: flex` then `justify-content: space between`.
- [ ] Lastly the footer has two blocks of text to the left, Kindly add a second paragraph so as to match the design

#### Your design
![image](https://user-images.githubusercontent.com/81932478/190403214-82b7fb71-9432-4bb7-842a-4aba7395255e.png)

#### Given design
![image](https://user-images.githubusercontent.com/81932478/190403344-1aedb346-a90c-4966-aaa1-a453c5dba38f.png)

2022-09-15 13:42 UTC, Munsa1 commented on about.html
> +        </div>
- [ ] The about page does not have the `Partners` section, kindly remove it.

#### Your design
![image](https://user-images.githubusercontent.com/81932478/190405177-2cc121f3-01ed-4f4f-9d1b-4bbed6c2abba.png)

#### Given design
![image](https://user-images.githubusercontent.com/81932478/190405322-e16f8063-2567-4a3f-8eda-b39da0815246.png)

2022-09-15 13:42 UTC, Munsa1 commented on index.html
> +            </div>
- [ ] Kindly  Increase the margin from ther left so as to make your design look similar to the given design
- [ ] Also increase the font size for the h1 tag so as to make it look more similar to the given design

#### Given design
![image](https://user-images.githubusercontent.com/81932478/190408203-e63a6681-e57c-4f2d-9d0e-80ecb0e6e167.png)

#### Your design
![image](https://user-images.githubusercontent.com/81932478/190408337-314a368f-7b27-4cad-8d61-d49f66020fab.png)

2022-09-15 13:42 UTC, Munsa1 commented on index.html
> +       <div id="desk_facts">
- [ ] These articles are five and not six kindly fix this, also they have to be wrapped in an article tag and not the div tag

#### Your design
![image](https://user-images.githubusercontent.com/81932478/190414931-16c9bc72-999e-4d96-af7c-5e08fd4b0fab.png)

#### Given design
![image](https://user-images.githubusercontent.com/81932478/190415075-e0933611-0ceb-449b-bd67-ec9808d5e382.png)

2022-09-15 17:41 UTC, jasonfelice approved these changes
Hi @Mike-devloper, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<p align="center"><img  src="https://media2.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=ecf05e472vkr75z01b5qlseyap0ylpyn6krdcf0fokyey0cx&rid=giphy.gif&ct=g"/></p>

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._ons or comments in the PR thread if something is not 100% clear.

2022-09-15 18:58 UTC, merged

2023-03-06 18:28 UTC, oguntayomicheal commented on about.html
> +    </footer>
Hi @Munsa1, thanks for the review. All required changes would be implemented.

2023-03-06 18:29 UTC, oguntayomicheal commented
Hi @jasonfelice, thanks for the review and project approval.